services:
  database:
    image: postgres:15-bullseye
    container_name: todo-database
    ports:
      - 5432:5432
    
    environment:
      - POSTGRES_USER=jradmin
      - POSTGRES_PASSWORD=12345678
      - POSTGRES_DB=TodoDb

  todolist:
    image: ${DOCKER_REGISTRY-}todolist
    container_name: todo-api
    build:
      context: .
      dockerfile: TodoList/Dockerfile
    ports:
      - "3000:3000"
      - "3001:3001"
    depends_on: 
      - database

    restart: on-failure

    develop:
      watch:
        - path: ./
          action: rebuild