services:
  database:
    image: postgres:15-bullseye
    container_name: todo-database
    ports:
      - 5432:5432
    env_file: ".env"
    environment:
      - POSTGRES_USER=${USER}
      - POSTGRES_PASSWORD=${PASSWORD}
      - POSTGRES_DB=${DATABASE}

  todolist:
    image: ${DOCKER_REGISTRY-}todolist
    container_name: todo-api
    build:
      context: .
      dockerfile: TodoList/Dockerfile
    ports:
      - "3000:3000"
      - "3001:3001"
    depends_on: 
      - database

    restart: on-failure

    env_file: ".env"
    environment:
      - HOST=${HOST}
      - PORT=${PORT}
      - USER=${USER}
      - PASSWORD=${PASSWORD}
      - DATABASE=${DATABASE}
